obj-y := kernpass/
obj-y += add_constraint_pass.o add_counter_pass.o array.o bpf_ir.o cut_bb_pass.o disasm.o ir_bb.o ir_code_gen.o ir_helper.o ir_insn.o ir_value.o lii.o optimization.o phi_pass.o prog_check.o
