obj-y := kernpass/
obj-y += array.o bpf_ir.o cg_prepare.o cg_prog_check.o code_compaction.o disasm.o div_by_zero.o hashtbl.o insn_counter_pass.o ir_bb.o ir_cg.o ir_cg_norm.o ir_cg_norm_v2.o ir_cg_v2.o ir_helper.o ir_insn.o ir_utils.o ir_value.o jmp_complexity.o kern_utils.o lli.o msan.o optimization.o phi_pass.o prog_check.o ptrset.o translate_throw.o
