obj-y := kernpass/
obj-y += add_counter_pass.o array.o bpf_ir.o cg_prepare.o disasm.o div_by_zero.o ir_bb.o ir_code_gen.o ir_helper.o ir_insn.o ir_utils.o ir_value.o kern_utils.o lii.o msan.o optimization.o phi_pass.o prog_check.o translate_throw.o
